[build]
  functions = "functions"
  publish = "uploads"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/images/*"
  to = "/uploads/:splat"
  status = 200